services:
  tempo:
    image: grafana/tempo:2.3.0
    command:
      - -config.file=/etc/tempo.yml
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./tempo-data:/tmp/tempo
    networks:
      - contestsubmission
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http

networks:
  contestsubmission:
    external: true
