:icons: font
:sectnums:    // Number all section titles
:toc: left
:experimental:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Infrastructure

ContestSubmission requires a handfull of services to function.

== Database
PostgreSQL is used as the database. For now, the DB is handled by Quarkus.
In the future, kubernetes configs will be provided. This is also how the DB will be deployed in production.

== Object Storage
Rather than storing files locally, ContestSubmission utilizes an object storage service to store files. +
For this, link:https://docs.quarkiverse.io/quarkus-amazon-services/dev/amazon-s3.html[quarkus' S3 Library],
which is based on the link:https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x],
is used.

While this might seem like a vendor lock-in, it _shouldn't_ be one.
That is because link:https://en.wikipedia.org/wiki/Amazon_S3[S3] is a de-facto standard for object storage. Plenty of
other services, like link:https://en.wikipedia.org/wiki/Google_Cloud_Storage[GCP's Cloud Storage] or
link:https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm[Oracle's Object Storage]
are compatible with S3. Not only that, for managed deployments, the open source link:https://min.io/[MinIO]
can be used as a drop-in replacement for proprietary cloud services.

In development, quarkus automatically launches a link:https://docs.localstack.cloud/user-guide/aws/s3/[re-implementation of S3], powered by
link:https://localstack.cloud[LocalStack].

== Monitoring
Monitoring is Jakob's favorite topic, therefore, a lot of effort has gone into making sure that ContestSubmission is
observable down to the finest detail.

Since monitoring is such a broad topic, two separate stacks are used.

=== Local
In local development, the application is monitored using link:https://grafana.com/oss/tempo/[Tempo],
link:https://prometheus.io/[Prometheus] and link:https://grafana.com/oss/grafana/[Grafana].

These applications have to be deployed manually, the configs are located under `infra/` in the repository root.

WARNING: Make sure to run the `create-network.sh` script before deploying the stack!

The stack is modularized into its components, you'll have to run the `docker compose up` in each directory.

TIP: Sometimes, a README is included in the directory, make sure to read it!

=== Staging / Prod
In staging / prod, a industry-grade monitoring solution is used: link:https://dynatrace.com[Dynatrace].

Dynatrace can automatically monitor not only the application but also the underlying infrastructure.
This is crucial since the application was built for maximum performance and scalability, therefore requiring
deep insights in order to be able to optimize it.

== Authentication
Authentication is handled by an OIDC provider. In this case, link:https://casdoor.org/[Casdoor] is used.

Casdoor is a lightweight, open source, OIDC provider. It is easy to deploy and configure.

Contrary to the other services, Casdoor is not deployed using docker-compose, but rather using kubernetes.
The configs are located in a separate repository and are deployed using ArgoCD. In development, the configs can be
re-used with only some minor changes. +
The configs are located under link:https://github.com/ContestSubmission/GitOps/tree/main/casdoor[`infra/casdoor`] in the link:https://github.com/ContestSubmission/GitOps[GitOps repo]. +

=== Launching
To launch the stack, run the following command in the `infra/casdoor` directory:
[source,bash]
----
kubectl apply -k overlays/dev
----

(Production will get its own overlay in the future. This is also what will be deployed using ArgoCD.)

=== Configuring Quarkus
Don't forget to set these properties:
[source,properties]
----
# WARNING: IP may be different for minikube!
quarkus.oidc.auth-server-url=http://localhost:30100
# found in the casdoor config
quarkus.oidc.client-id=myclientid
# found in the casdoor config
quarkus.oidc.credentials.secret=myclientsecret
----
