package com.github.contestsubmission.backend.feature.user

import jakarta.persistence.Entity
import jakarta.persistence.Id
import java.util.*

@Entity
class Person(
	@Id
	/**
	 * The id is generated by the OIDC provider
	 * If you set this manually, you risk breaking the authentication
	 */
	var id: UUID? = null,
)
