package com.github.contestsubmission.backend.feature.user

import jakarta.persistence.Entity
import jakarta.persistence.Id
import java.util.*

@Entity
class Person(
	@Id
	/**
	 * The id is generated by the OIDC provider
	 * If you set this manually, you risk breaking the authentication
	 */
	var id: UUID? = null,
) {
	override fun equals(other: Any?): Boolean {
		if (this === other) return true
		if (other !is Person) return false

		if (id != other.id) return false

		return true
	}

	override fun hashCode(): Int {
		return id?.hashCode() ?: 0
	}
}
