on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          # won't be used but is required by the action
          images: ghcr.io/contestsubmission/contestsubmission-backend
          tags: |
            type=raw,{{ github.run_number }}-{{ github.run_id }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}

      - name: Build docker image
        run: |
          ./gradlew \
            -Dquarkus.container-image.group="contestsubmission" \
            -Dquarkus.container-image.name="contestsubmission-backend" \
            -Dquarkus.container-image.additional-tags="$DOCKER_METADATA_OUTPUT_TAGS" \
            imageBuild

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push --all-tags ghcr.io/contestsubmission/contestsubmission-backend
