on: push

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          # won't be used but is required by the action
          images: dummy
          tags: |
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
            type=ref,event=branch
            type=ref,event=pr
          labels: |
            com.github.actions.run.id=${{ github.run_id }}
            com.github.actions.run.number=${{ github.run_number }}
            com.github.actions.run.url=${{ github.run_url }}

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build docker image
        run: |
          additional_tags="$(echo "$DOCKER_METADATA_OUTPUT_TAGS" | tr '\n' ',' | sed 's/dummy://g')"
          labels="$(echo "$DOCKER_METADATA_OUTPUT_LABELS" | awk -F '=' '{print "quarkus.container-image.labels.\"" $1 "\"="$2}')"
          ./gradlew \
            -Dquarkus.container-image.group="contestsubmission" \
            -Dquarkus.container-image.name="contestsubmission-backend" \
            -Dquarkus.container-image.tag='${quarkus.application.version}-${{ github.run_number }}' \
            -Dquarkus.container-image.additional-tags="$additional_tags" \
            -Dquarkus.container-image.labels="$labels" \
            imageBuild

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push --all-tags ghcr.io/contestsubmission/contestsubmission-backend
